config/routes.rb
Toplist::Application.routes.draw do
  post "api/approve"
  
  devise_for :users
  resources :posts
  resources :comments

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	acts_as_commentable
	acts_as_taggable

	# helper functions for fetching pending and approved
	def self.pending
		where(status: 'pending')
	end

	def self.approved
		where(status: 'approved')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter

  has_many :comments, dependent: :destroy
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def approve
		# request to this action will attempt to like a post for the current user
		@post = Post.find(approve_params['post_id'])
		@post.liked_by current_user

		respond_to do |format|
      format.json { render json: @post.votes_for.count }
    end
	end

	private

		def approve_params
			params.require(:approve).permit(:post_id)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new

	end

	def create
		# @comment = Comment.new(comment_params)
    params = comment_params
    @post = Post.find(params['post_id'])
    @comment = @post.comments.new
    @comment.user_id = current_user.id
    @comment.comment = params['comment']
    respond_to do |format|
    	if @comment.save
    		# comment was successfully saved
    		format.html { redirect_to @post, notice: 'comment was successfully created.' }
	    else
	    	# error, there was a error!!
        format.html { redirect_to @post, notice: @comment.errors }
	    end
    end
    


    # # @comment.product_id = @product.id
    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @product, notice: 'comment was successfully created.' }
    #     # format.json { render action: 'show', status: :created, location: @comment }
    #   else
    #     format.html { redirect_to @product, notice: @comment.errors }
    #     # format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
	end

	def update

	end

	def edit

	end

	def destroy

	end

	private
		def comment_params
			params.require(:comment).permit(:comment, :post_id)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(@post.user_id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :link)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('https://s3.amazonaws.com/toplists/logo/logo_header.png'), root_path, class: "navbar-brand" %>
      
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= form_tag '#', method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search.' %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default", type: 'hidden' %>
          </p>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        
        <li><a href="#"><span class="glyphicon glyphicon-plus"></span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_newsletter.html.erb
<div class="container-fluid">
	<%= form_tag '#', method: :get, class: 'form-newsletter' do %>
    <p>
      <%= text_field_tag :email, params[:email], class: "form-control", placeholder: 'Email.' %>
      <%= submit_tag "GET NEWSLETTER", name: nil, class: "btn btn-default" %>
    </p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toplist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>

	<%= render 'layouts/newsletter' %>

	<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="show container-fluid">
  <div class="post">
    <input placeholder="# Of Things You Want To Share With The World" value=""/>
    <div class="post__thumbnail">COVER PHOTO</div>
    <div class="post__info">
      <div class="post__user-avatar"></div>
      <div class="post__user-name">@sheryl2</div>
    </div>

    <div class="post__body">
      <textarea rows="50" cols="100" placeholder="1. Title
      Say a little something about this."></textarea>
    </div>



  </div>

</div>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="home container-fluid">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post__user-avatar"></div> <div class="post__user-name">@atseng3</div>
      <div class="post__thumbnail"></div>
      <div class="post__title"><%= link_to post.title, post_path(post) %></div>
      <div class="post__stats">
        <span><%= post.votes_for.count %> approve</span>
        <span><%= post.comments.count %> comments</span>
      </div>
      <button class="btn btn-default approve">APPROVE</button>
      <button class="btn btn-default comment">COMMENT</button>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show container-fluid">
	<div class="post">
		<h1><%= @post.title %></h1>
		
		<div class="post__thumbnail"></div>
		
		<div class="post__info">
			<div class="post__user-avatar"></div>
			<!-- <div class="post__user-name">@sheryl2&nbsp;&nbsp;&middot;&nbsp;&nbsp;</div> -->
			<div class="post__user-name">@<%= /^\w+/.match(@user.email) %>&nbsp;&nbsp;&middot;&nbsp;&nbsp;</div>
			<div class="post__stats">

				<span id="post__approves"><%= @post.votes_for.count %></span> approve
			</div>
			<a id="approve" class="approve">APPROVE</a>
		</div>
		
		<div class="post__body">
			<h3>1. Total Body Movements.</h3>
			<p>
				At its core, success is about relationships. Involve customers and colleagues in the
				creation of and direction of your busines pursuits. With them, set standards for the
				work that needs to be accomplished in each person’s area of responsibility. Make 
				these standards challenging but achievable. The result will be the high-level 
				productivity and service you aim to perform. 
			</p>
			<p>
				You can only go so far in business alone. You need others for your own success, 
				empowerment and completeness. In business, choose your aims and equip your team
				to get your business where it needs to go, rewarding the team members along the way.
			</p>
			<h3>2. Total Body Movements.</h3>
			<p>
				At its core, success is about relationships. Involve customers and colleagues in the
				creation of and direction of your busines pursuits. With them, set standards for the
				work that needs to be accomplished in each person’s area of responsibility. Make 
				these standards challenging but achievable. The result will be the high-level 
				productivity and service you aim to perform. 
			</p>
			<p>
				You can only go so far in business alone. You need others for your own success, 
				empowerment and completeness. In business, choose your aims and equip your team
				to get your business where it needs to go, rewarding the team members along the way.
			</p>
			<h3>3. Total Body Movements.</h3>
			<p>
				At its core, success is about relationships. Involve customers and colleagues in the
				creation of and direction of your busines pursuits. With them, set standards for the
				work that needs to be accomplished in each person’s area of responsibility. Make 
				these standards challenging but achievable. The result will be the high-level 
				productivity and service you aim to perform. 
			</p>
			<p>
				You can only go so far in business alone. You need others for your own success, 
				empowerment and completeness. In business, choose your aims and equip your team
				to get your business where it needs to go, rewarding the team members along the way.
			</p>
				
		</div>
	</div>
</div>

<div class="show container-fluid">
	<div class="comments">
		<div class="row comment-title">
			All Comments (<%= @post.comments.count %>)
		</div>
		<div class="row new-comment">
			<div class="user-avatar col-md-2 col-xs-4"></div>
			<%= form_tag comments_url, method: :post, class: "col-md-10 col-xs-8" do %>
	      <p>
	        <%= text_area(:comment, :comment, class: "form-control", placeholder: 'Add a Comment') %>
	        <input type="hidden" name="comment[post_id]" value=<%= @post.id %> />
	        <%= submit_tag "Post", name: nil, class: "btn btn-default new-comment__submit" %>
	      </p>
	    <% end %>
		</div>
		<% @post.comments.each do |comment| %>
			<div class="comment row">
				<div class="user-avatar col-md-2 col-xs-4">
				</div>
				<div class="comment__content col-md-10 col-xs-8">
					<div class="user-name">@atseng3</div> <%= time_ago_in_words(comment.created_at) %> ago
					<div class="comment__body">
						<%= raw comment.comment %>
					</div>
				</div>
			</div>	
		<% end %>
	</div>
</div>

<script type="text/javascript">
$('#approve').click(function(event) {
	event.preventDefault();
	// debugger
	var post_id = $('input[name="comment[post_id]"]').val();
	$.ajax({
		url: '/api/approve',
		type: 'POST',
		data: {
			approve: {
				post_id: post_id
			}
		},
		success: function(num_approvals) {
			// update num_approvals upon success
			var approve_el = document.getElementById('post__approves');
			approve_el.innerHTML = num_approvals;
		}
	});
});
</script>